#!/usr/bin/env python3
"""Generate manuscript tables from frozen downstream summary artifacts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


TOOLS = ("seqproc", "splitcode", "matchbox")
PAIR_ORDER = ("seqproc|splitcode", "seqproc|matchbox", "splitcode|matchbox")
TOOL_TEX = {"seqproc": r"\seqproc", "splitcode": r"\splitcode", "matchbox": r"\matchbox"}
TYPE_ORDER = ("Neuron", "Astrocyte", "Oligodendro", "OPC", "Microglia", "Endothelial")
TYPE_LABEL = {"Oligodendro": "Oligodendrocyte"}


def load_summary(path: Path) -> dict:
    if path.is_dir():
        path = path / "downstream_summary.json"
    return json.loads(path.read_text())


def latex_int(value: int) -> str:
    return f"{value:,}".replace(",", "{,}")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("% Generated by write_downstream_latex_tables.py; do not edit by hand.\n" + text)


def main_table(summary: dict) -> str:
    rows = []
    for pair in PAIR_ORDER:
        left, right = pair.split("|")
        metrics = summary["pairs"][pair]
        rows.append(
            f"{TOOL_TEX[left]} / {TOOL_TEX[right]} & "
            f"{metrics['per_gene_pearson_log1p']:.3f} & "
            f"{metrics['per_barcode_pearson_log1p']:.3f} & "
            f"{metrics['celltype_agreement']:.3f} & "
            f"{metrics['celltype_jaccard_mean']:.3f} & {metrics['cluster_ari']:.3f} \\\\"
        )
    return rf"""\begin{{table*}}[t]
\centering
\changed
\begin{{adjustbox}}{{width=\textwidth}}
\begin{{tabular}}{{@{{}}lrrrrr@{{}}}}
\toprule
Tool pair & Per-gene Pearson & Per-barcode Pearson & Cell-type agreement & Mean type Jaccard & Cluster ARI \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{adjustbox}}
\caption{{\changed{{Pairwise downstream concordance for the final SPLiT-seq PE outputs under the common \textsc{{STARsolo}} \texttt{{CB\_UMI\_Complex}} \texttt{{EditDist\_2}} configuration. The primary \matchbox input uses canonical-barcode matching, edit-distance-three linker matching, and explicit captured-component length guards. Pearson correlations use total UMI counts on the $\log(1+x)$ scale. Cell-type agreement, mean Jaccard over the six marker-based cell types, and adjusted Rand index (ARI) are calculated on the cells called by all three tools.}}}}
\label{{tab:pairwise_concordance}}
\end{{table*}}
"""


def jaccard_table(summary: dict) -> str:
    rows = []
    for cell_type in TYPE_ORDER:
        values = [summary["celltype_jaccard_pairwise_per_type"][pair][cell_type] for pair in PAIR_ORDER]
        rows.append(
            f"{TYPE_LABEL.get(cell_type, cell_type)} & "
            + " & ".join(f"{value:.3f}" for value in values)
            + f" & {summary['celltype_jaccard_per_type'][cell_type]:.3f} \\\\"
        )
    return rf"""\begin{{table}}[H]
\centering
\changed
\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\toprule
Cell type & SP/SC & SP/MB & SC/MB & Mean \\
\midrule
{chr(10).join(rows)}
\midrule
Mean & {summary['celltype_jaccard_pairwise_mean']['seqproc|splitcode']:.3f} & {summary['celltype_jaccard_pairwise_mean']['seqproc|matchbox']:.3f} & {summary['celltype_jaccard_pairwise_mean']['splitcode|matchbox']:.3f} & {summary['celltype_jaccard_mean']:.3f} \\
\bottomrule
\end{{tabular}}
\caption{{\changed{{Pairwise per-cell-type Jaccard index of marker-based labels over the {summary['shared_cells']} cells called by all three tools. SP, SC, and MB denote \seqproc, \splitcode, and canonical-barcode/fuzzy-linker \matchbox. The final column and row retain the across-pair summaries.}}}}
\label{{tab:jaccard}}
\end{{table}}
"""


def sensitivity_table(summaries: list[tuple[str, dict]]) -> str:
    rows = []
    for label, summary in summaries:
        matchbox = summary["tools"]["matchbox"]
        cells = "/".join(str(summary["tools"][tool]["called_cells_min_umi"]) for tool in TOOLS)
        min_gene = min(summary["pairs"][pair]["per_gene_pearson_log1p"] for pair in PAIR_ORDER)
        min_barcode = min(summary["pairs"][pair]["per_barcode_pearson_log1p"] for pair in PAIR_ORDER)
        rows.append(
            f"{label} & {latex_int(matchbox['input_pairs'])} & "
            f"{100 * matchbox['STARsolo']['Reads With Valid Barcodes']:.2f} & {cells} & "
            f"{summary['all_tool_celltype_agreement']:.3f} & {summary['celltype_jaccard_mean']:.3f} & "
            f"{min_gene:.3f} & {min_barcode:.3f} \\\\"
        )

    return rf"""\begin{{minipage}}{{\textwidth}}
\centering
\changed
\resizebox{{\textwidth}}{{!}}{{%
\begin{{tabular}}{{@{{}}lrrrrrrr@{{}}}}
\toprule
Configuration & Matchbox reads & Valid BC (\%) & Cells (SP/SC/MB) & All-type & Mean Jaccard & Min. gene $r$ & Min. barcode $r$ \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}}}
\captionof{{table}}{{\changed{{Sensitivity of the downstream analysis to \textsc{{STARsolo}} barcode correction and to external Hamming-1 expansion of the canonical \matchbox barcode lists. All \matchbox variants use edit-distance-three linker matching and captured-component length guards. SP, SC, and MB denote \seqproc, \splitcode, and \matchbox. ``Min.'' is the least favorable value among the three tool pairs, avoiding post hoc selection of a favorable comparison.}}}}
\label{{tab:downstream_sensitivities}}
\end{{minipage}}
"""


def pairwise_sensitivity_table(summaries: list[tuple[str, dict]]) -> str:
    rows = []
    pair_labels = {
        "seqproc|splitcode": "SP/SC",
        "seqproc|matchbox": "SP/MB",
        "splitcode|matchbox": "SC/MB",
    }
    for label, summary in summaries:
        for pair_index, pair in enumerate(PAIR_ORDER):
            metrics = summary["pairs"][pair]
            configuration = rf"\multirow{{3}}{{*}}{{{label}}}" if pair_index == 0 else ""
            rows.append(
                f"{configuration} & {pair_labels[pair]} & "
                f"{metrics['celltype_agreement']:.3f} & "
                f"{metrics['celltype_jaccard_mean']:.3f} & "
                f"{metrics['cluster_ari']:.3f} \\\\"
            )
        rows.append(r"\addlinespace[0.2em]")

    return rf"""\begin{{minipage}}{{\textwidth}}
\centering
\changed
\footnotesize
\begin{{tabular}}{{@{{}}llrrr@{{}}}}
\toprule
Configuration & Pair & Cell-type agreement & Mean type Jaccard & Cluster ARI \\
\midrule
{chr(10).join(rows[:-1])}
\bottomrule
\end{{tabular}}
\captionof{{table}}{{\changed{{Pairwise shared-cell biological concordance underlying the aggregate sensitivity scorecard in \Cref{{fig:downstream_sensitivities}}. SP, SC, and MB denote \seqproc, \splitcode, and \matchbox. Mean type Jaccard is the unweighted mean over the six marker-based cell types.}}}}
\label{{tab:downstream_pairwise_sensitivities}}
\end{{minipage}}
"""


def accuracy_table(accuracy: dict) -> str:
    accuracy_rows = []
    key_pairs = (
        ("Canonical barcodes", ("canonical-fuzzy", "matchbox_exact")),
        ("Hamming-1-expanded barcodes", ("ham1-expanded-fuzzy", "matchbox_expanded")),
    )
    for label, candidate_keys in key_pairs:
        key = next((candidate for candidate in candidate_keys if candidate in accuracy["tools"]), None)
        if key is None:
            raise KeyError(f"none of {candidate_keys!r} found in accuracy artifact")
        values = accuracy["tools"][key]
        accuracy_rows.append(
            f"{label} & {latex_int(values['emitted_records'])} & "
            f"{100 * values['precision']:.2f} & {100 * values['recall']:.2f} & {values['f1']:.4f} \\\\"
        )

    return rf"""\begin{{table}}[H]
\centering
\changed
\resizebox{{\columnwidth}}{{!}}{{%
\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\toprule
\matchbox barcode list & Emitted reads & Precision (\%) & Recall (\%) & F1 \\
\midrule
{chr(10).join(accuracy_rows)}
\bottomrule
\end{{tabular}}}}
\caption{{\changed{{Structural-reference sensitivity for canonical and externally Hamming-1-expanded \matchbox barcode lists, both with edit-distance-three linker matching and captured-component length guards. Precision and recall are agreement with the conservative structurally retained set, not biological ground truth.}}}}
\label{{tab:matchbox_expansion_accuracy}}
\end{{table}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exact-editdist2", type=Path, required=True)
    parser.add_argument("--exact-1mm", type=Path, required=True)
    parser.add_argument("--expanded-editdist2", type=Path, required=True)
    parser.add_argument("--expanded-1mm", type=Path, required=True)
    parser.add_argument("--accuracy", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    exact_editdist2 = load_summary(args.exact_editdist2)
    summaries = [
        (r"Canonical + \texttt{EditDist\_2}", exact_editdist2),
        (r"Canonical + \texttt{1MM}", load_summary(args.exact_1mm)),
        (r"Expanded + \texttt{EditDist\_2}", load_summary(args.expanded_editdist2)),
        (r"Expanded + \texttt{1MM}", load_summary(args.expanded_1mm)),
    ]
    accuracy = json.loads(args.accuracy.read_text())

    write(args.output_dir / "generated_downstream_main_table.tex", main_table(exact_editdist2))
    write(args.output_dir / "generated_downstream_jaccard_table.tex", jaccard_table(exact_editdist2))
    write(
        args.output_dir / "generated_downstream_sensitivity_table.tex",
        sensitivity_table(summaries),
    )
    write(
        args.output_dir / "generated_downstream_pairwise_sensitivity_table.tex",
        pairwise_sensitivity_table(summaries),
    )
    write(args.output_dir / "generated_matchbox_expansion_table.tex", accuracy_table(accuracy))


if __name__ == "__main__":
    main()
